#ifndef _RAY_OBJECT_TYPE_H
#define _RAY_OBJECT_TYPE_H

typedef enum ray_object_type_t {
	RAY_OBJECT_TYPE_SENTINEL,
	RAY_OBJECT_TYPE_SPHERE,
	RAY_OBJECT_TYPE_POINT,
	RAY_OBJECT_TYPE_PLANE,
	RAY_OBJECT_TYPE_LIGHT,
} ray_object_type_t;

#endif
